In [2]:
import numpy as np
import matplotlib.pyplot as plt
import torch

In [10]:
# Question 1

# a + b
a = torch.randn(256, 256, 3)
b = torch.randn(3, )

# print(a)
print(b)
c = a + b
print(a + b)
print("shape of a+b: ", c.shape)

tensor([ 0.5326, -0.9852,  1.4323])
tensor([[[ 0.2569,  0.1824,  0.5560],
         [ 1.1677,  0.7864,  0.4633],
         [ 1.0062,  0.7750,  0.5920],
         ...,
         [ 2.3666, -3.0112,  3.1296],
         [ 1.5233, -0.7003,  2.6729],
         [ 0.5104, -0.1181,  0.5898]],

        [[ 0.1451, -1.9456,  1.2210],
         [ 0.4327,  0.2485,  2.1030],
         [-0.0566, -2.5209,  0.5707],
         ...,
         [ 0.3648,  0.4728,  2.8926],
         [ 0.4328, -1.4612, -0.0870],
         [-0.5739, -0.9278,  0.1273]],

        [[-0.2190, -2.7304,  0.0665],
         [-0.2584,  0.7486,  2.3157],
         [-0.0130, -0.8431,  2.0532],
         ...,
         [ 1.5957, -1.6160,  1.1896],
         [ 0.5691, -1.4558,  3.6924],
         [ 1.0496, -0.1551,  1.9503]],

        ...,

        [[ 0.3519, -1.0618,  2.8928],
         [-0.7243, -1.2394,  1.7956],
         [-1.3903, -3.3179,  2.6307],
         ...,
         [ 0.6322, -2.1007,  1.8944],
         [-0.2826, -1.6059,  0.2583],
         [-0.2

In [13]:
# a - b
a = torch.randn(10, 2, 6, 1)
b  =torch.randn(9, 1, 7)

c = a - b
print(a - b)
print("shape of a-b: ", c.shape)

RuntimeError: The size of tensor a (2) must match the size of tensor b (9) at non-singleton dimension 1

In [12]:
# a * b
a = torch.randn(2, )
b = torch.randn(4, )

c = a * b
print(a * b)
print("shape of a*b: ", c.shape)

RuntimeError: The size of tensor a (2) must match the size of tensor b (4) at non-singleton dimension 0

In [13]:
# a / b
a = torch.randn(4, 1)
b = torch.randn(8, 5, 3)

c = a / b
print(a / b)
print("shape of a/b: ", c.shape)

RuntimeError: The size of tensor a (4) must match the size of tensor b (5) at non-singleton dimension 1

In [14]:
# a - b
a = torch.randn(5, 3, 2)
b  =torch.randn(5, 1, 2)

c = a - b
print(a - b)
print("shape of a-b: ", c.shape)

tensor([[[-1.7309, -1.3702],
         [-1.4528,  0.1082],
         [ 0.0153, -0.1580]],

        [[-1.7011, -1.5007],
         [ 0.4616,  0.2882],
         [ 0.6490, -1.2847]],

        [[ 1.0765,  0.2060],
         [ 0.7291,  1.1663],
         [ 0.7049,  1.3727]],

        [[ 0.8061, -1.1776],
         [ 2.6355,  0.0448],
         [ 1.6704, -0.3918]],

        [[ 0.0594,  0.3879],
         [-0.2301,  0.2670],
         [ 1.4516,  2.0242]]])
shape of a-b:  torch.Size([5, 3, 2])


In [27]:
# a - b.mean()
a = torch.randn(128, 128, 3)
b  =torch.randn(256, 128, 5)
d = b.mean(axis=(0,2),keepdims=True)
print(d.shape)
# c = a - b.mean()
# print(c)
# print("shape of a-b.mean(): ", c.shape)

torch.Size([1, 128, 1])


In [16]:
# a - b.mean(axis=(1, 2))
a = torch.randn(3, 256, 256)
b  =torch.randn(3, 256, 256)

c = a - b.mean(axis=(1, 2))
print(c)
print("shape of a-b.mean(axis=(1, 2)): ", c.shape)

RuntimeError: The size of tensor a (256) must match the size of tensor b (3) at non-singleton dimension 2

In [17]:
# a - b.mean(axis=(1, 2), keepdims=True)
a = torch.randn(3, 256, 256)
b  =torch.randn(3, 256, 256)

c = a - b.mean(axis=(1, 2), keepdims=True)
print(c)
print("shape of a-b.mean(axis=(1, 2), keepdims=True): ", c.shape)

tensor([[[-2.2395,  0.0247, -1.5721,  ..., -0.3044, -1.1629, -0.3098],
         [-0.9250, -1.4303, -0.7383,  ...,  0.3482,  0.6283, -0.3130],
         [ 0.9786, -0.5869, -1.2731,  ...,  0.1095, -1.2083, -0.3547],
         ...,
         [-0.2001,  0.5430, -0.0252,  ..., -0.5303,  0.1550,  1.1469],
         [-0.2200,  0.2501,  1.0996,  ..., -1.1276, -1.3612, -3.4823],
         [-0.2161,  0.9807,  0.5511,  ..., -0.5383, -1.9823, -1.1695]],

        [[-0.2642,  0.0618, -0.3088,  ..., -0.3509,  0.3341,  0.5641],
         [-1.5980,  0.3693,  0.7544,  ..., -0.3001, -0.3082,  0.6980],
         [-0.4137,  0.5009,  0.9219,  ..., -0.1386, -0.7766, -1.2497],
         ...,
         [ 0.1104, -0.5222, -0.4684,  ...,  0.0548, -0.7141, -0.0599],
         [ 0.2632, -0.1616, -0.4961,  ..., -0.8813,  1.5873, -1.6117],
         [ 0.4254, -0.2297, -0.7302,  ...,  0.5846,  2.4447, -0.9767]],

        [[ 0.6228,  0.4188, -0.3582,  ...,  1.8908,  0.7606,  0.4153],
         [-0.9307, -0.3632,  0.8036,  ...,  1

In [29]:
# np.matmul(a, b)
a = torch.randn(7,6, 5, 3)
b  =torch.randn(4, 4)

c = np.matmul(a, b)
print(c)
print("shape of np.matmul(a, b): ", c.shape)

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 4 is different from 3)

In [10]:
# Question 2
import numpy as np

# m = int(input())
# n = int(input())
# d = int(input())
# shape_x = (m, d)
# shape_y = (n, d)

# X = np.random.randn(*shape_x)
# Y = np.random.randn(*shape_y)

X = np.array([[1,2,3],[2,3,4],[3,4,5],[4,5,6],[5,6,7]])
Y = np.array([[1,1,1],[1,1,1],[1,1,1],[1,1,1]])

M = X.shape[0]
N = Y.shape[0]

assert X.shape[1] == Y.shape[1]

X_dots = (X*X).sum(axis=1).reshape((M,1))*np.ones(shape=(1,N))
Y_dots = (Y*Y).sum(axis=1)*np.ones(shape=(M,1))

D_squared =  X_dots + Y_dots -2*X.dot(Y.T)

print(D_squared)
print("shape of the output: ", D_squared.shape)

[[ 5.  5.  5.  5.]
 [14. 14. 14. 14.]
 [29. 29. 29. 29.]
 [50. 50. 50. 50.]
 [77. 77. 77. 77.]]
shape of the output:  (5, 4)


In [9]:
import numpy as np

# Define the dimensions of the matrix
m = 5
n = 4
d = 3

# Create random matrices
A = np.random.rand(m, d)
B = np.random.rand(n, d)

# Optimized function to compute squared Euclidean distances
def compute_squared_distances_optimized(A, B):
    # Using broadcasting to compute the squared Euclidean distances
    A_exp = A[:, np.newaxis, :]  # Expand A to shape (m, 1, d)
    B_exp = B[np.newaxis, :, :]  # Expand B to shape (1, n, d)
    
    # Compute the pairwise squared differences
    D = np.sum((A_exp - B_exp)**2, axis=2) ** 0.5 # Sum over the last axis (dimension)

    # The following code will also perform a similar operation 
    # Compute the Euclidean norm (L2) across the last axis and square the result
    # D = np.linalg.norm(A_exp - B_exp, axis=2) 

    return D

# Compute the distances
D_optimized = compute_squared_distances_optimized(A, B)

print(D_optimized)


[[2.23606798 2.23606798 2.23606798 2.23606798]
 [3.74165739 3.74165739 3.74165739 3.74165739]
 [5.38516481 5.38516481 5.38516481 5.38516481]
 [7.07106781 7.07106781 7.07106781 7.07106781]
 [8.77496439 8.77496439 8.77496439 8.77496439]]


In [12]:
import numpy as np

# Define the dimensions of the matrix
m = 5
n = 4
d = 3

# Create random matrices
A = np.random.rand(m, d)
B = np.random.rand(n, d)

# Function to compute squared Euclidean distances using np.linalg.norm
def compute_squared_distances_norm(A, B):
    # Reshape and broadcast A and B to compute pairwise distances
    A_exp = A[:, np.newaxis, :]  # Expand A to shape (m, 1, d)
    B_exp = B[np.newaxis, :, :]  # Expand B to shape (1, n, d)
    
    # Compute the Euclidean norm (L2) across the last axis and square the result
    D = np.linalg.norm(A_exp - B_exp, axis=2)
    return D

# Compute the distances
D_norm = compute_squared_distances_norm(A, B)

print(D_norm)


[[0.41406258 0.5535224  0.26561949 0.75226057]
 [0.79276466 0.48239039 0.65547999 0.31796679]
 [0.84623284 0.54582536 0.58764972 0.95103103]
 [0.54530051 0.86013369 0.23080766 0.88510572]
 [0.66393211 0.32556835 0.75397319 0.76940679]]
